# Logistic Regression

In [6]:
import pandas as pd
import numpy as np

In [5]:
from sklearn.datasets import load_iris

In [2]:
dataset = load_iris()

In [3]:
print(dataset.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [4]:
dataset.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [7]:
df = pd.DataFrame(dataset.data,columns=dataset.feature_names)

In [8]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [9]:
df['target'] = dataset.target

In [10]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [11]:
df['target'].unique()

array([0, 1, 2])

In [12]:
#Here we need only two classes. So we are removing class 2 from out dataset
df_copy = df[df['target']!=2]

In [14]:
df_copy['target'].unique()

array([0, 1])

In [16]:
#Independent and Dependent features
X = df_copy.iloc[:,:-1]
y = df_copy.iloc[:,-1]

In [17]:
#Train Test Split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.20,random_state=42)

In [23]:
#Logistic Regression Model
from sklearn.linear_model import LogisticRegression
regressor = LogisticRegression(max_iter=200)                #when max_iter not given. 
                                                            #Pwskills: it is showing an warning that i could'nt reach global minima.

In [24]:
regressor.fit(X_train,y_train)

LogisticRegression(max_iter=200)

In [25]:
y_pred = regressor.predict(X_test)

In [22]:
y_pred

array([1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0])

## Confusion matrix, Accuracy, Classification Report

In [26]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [27]:
print(confusion_matrix(y_test,y_pred))

[[12  0]
 [ 0  8]]


In [28]:
print(accuracy_score(y_test,y_pred))

1.0


In [29]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      1.00      1.00         8

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



## Cross Validation

In [30]:
from sklearn.model_selection import KFold

In [31]:
cv=KFold(n_splits=5)

In [33]:
from sklearn.model_selection import cross_val_score

In [34]:
score = cross_val_score(regressor,X_train,y_train,scoring='accuracy',cv=cv)

In [35]:
##these are the scores all the cross validation
score

array([1., 1., 1., 1., 1.])

In [36]:
np.mean(score)

1.0